name: goodealz
description: A new Flutter project.
publish_to: 'none'
version: 1.2.0+6

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  shared_preferences: ^2.2.0
  dio: ^5.3.2
  provider: ^6.0.5
  flutter_svg: ^2.2.1
  pinput: ^5.0.2
  cached_network_image: ^3.2.3
  pretty_dio_logger: ^1.3.1
  cupertino_icons: ^1.0.2
  square_progress_bar: ^1.1.1
  slide_countdown: ^2.0.2
  scroll_page_view: ^1.0.2
  firebase_messaging: ^16.0.1
  firebase_core: ^4.1.0
  flutter_local_notifications: ^19.4.2
#  pusher_beams: ^1.1.1
#  pusher_channels_flutter: ^2.4.0
  dropdown_search: ^5.0.6
  fancy_shimmer_image: ^2.0.2
#  location_picker_flutter_map: ^2.1.0
#  google_maps_flutter: ^2.6.0
  geolocator: ^14.0.2
  flick_video_player: ^0.9.0
  video_player: ^2.8.3
  pull_to_refresh_flutter3: ^2.0.2
  image_picker: ^1.0.7
  google_sign_in: ^7.2.0
  flutter_facebook_auth: ^7.1.2
  firebase_auth: ^6.0.2
  flutter_spinkit: ^5.2.2
  percent_indicator: ^4.2.3
  url_launcher: ^6.3.2
  url_launcher_ios: ^6.3.2
  flutter_html: ^3.0.0-beta.2
  connectivity_plus: ^7.0.0
  #  map_location_picker: ^1.2.8+3
  pull_refresh_widget: ^0.0.3
  webview_flutter: ^4.13.0
  country_code_picker: ^3.4.1
  carousel_custom_slider: ^0.0.7+3
  shimmer: ^3.0.0
  sign_in_with_apple: ^7.0.1
  geocoding: ^4.0.0
  google_maps_flutter: ^2.6.1
#  flutter_google_places: ^0.3.0
  google_api_headers: ^4.6.0

  share_plus: ^12.0.1
  screenshot: ^3.0.0
  path_provider: ^2.1.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21

flutter:

  uses-material-design: true

  assets:
    - assets/lang/
    - assets/images/
    - assets/svgs/
    - assets/data/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-ExtraLight.ttf
          weight: 100
        - asset: assets/fonts/Poppins/Poppins-Thin.ttf
          weight: 200
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-Black.ttf
          weight: 800
        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 900
